language: node_js

node_js:
 - "8"
 - "10"

dist: trusty
sudo: true

services:
  - memcached
  - redis-server

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

notifications:
  email:
    - rfkelly@mozilla.com
    - jrgm@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

_aliases:
  - &test
    before_install:
    - npm i -g npm@6
    - npm config set spin false
  - &fxa-auth-memory-test
    env: DB=memory
    <<: *test
  - &fxa-auth-mysql-test
    env: DB=mysql
    <<: *test
  - &fxa-oauth-memory-test
    env: CXX=g++-4.8 NODE_ENV=test DB=memory
    <<: *test
  - &fxa-oauth-mysql-test
    env: CXX=g++-4.8 NODE_ENV=test DB=mysql
    <<: *test

jobs:
  include:
  - stage:
    node_js:
    - "8"
    - "10"
    <<: *fxa-auth-memory-test
    install:
      - npm ci
    script:
      - npm run test-ci
      - npm run test-e2e
      - NODE_ENV=test npm run test-scripts
      - grunt templates && git status -s | (! grep 'M lib/senders/templates/')
      - grunt l10n-extract
      - npm run lint:deps
  - stage:
    node_js:
    - "8"
    - "10"
    <<: *fxa-auth-mysql-test
    install:
      - npm ci
    script:
      - ./scripts/start-travis-auth-db-mysql.sh
      - npm run test-ci
      - npm run test-e2e
  - stage:
    node_js: 8
    <<: *fxa-oauth-memory-test
    install:
      - npm ci
    script: npm run test-oauth
  - stage:
    node_js: 8
    <<: *fxa-oauth-memory-test
    install:
      - npm ci
    script: npm run test-oauth
