language: node_js

node_js:
  - '0.10'
  - '4'

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  email:
    smcarthur@mozilla.com
    jrgm@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

env:
  - NODE_ENV=test DB=memory
  - NODE_ENV=test DB=mysql

before_install:
  - npm install -g npm@2
  - npm config set spin false

install:
  # use c++-11 with node4, default compiler on downlevel versions
  - if [ $TRAVIS_NODE_VERSION == "4" ]; then CXX=g++-4.8 npm install; else npm install; fi

before_script:
  - "mysql -NBe 'select version()'"
  - "mysql -e 'DROP DATABASE IF EXISTS fxa_oauth;'"
  - "mysql -e 'CREATE DATABASE fxa_oauth;'"

script:
  - npm run outdated
  - grunt test
  - grunt nsp --force
