language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

os:
  - linux

addons:
  apt_packages:
    - graphicsmagick
    - python-virtualenv
    - libgmp3-dev
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - docker-ce

env:
  matrix:
  - TRAVIS_NODE_VERSION="10"

matrix:
  allow_failures:
    - os: osx
    - fast_finish: true

before_install:
  - npm i -g npm@6
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install graphicsmagick; fi

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - npm install -g npm@6
  - node --version
  - npm --version
  - curl -sSf https://sh.rustup.rs | sh -s -- -y --verbose
  - PATH=$PATH:$HOME/.cargo/bin
  - rustup install nightly-2018-06-23
  - rustc --version

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup

script:
  - npm config set spin false
  - npm install
  - ./test/curl.sh
  - pm2 kill
  - pm2 start mysql_servers.json
  - ./test/mysql.sh

after_failure:
  - pm2 status
