language: node_js
node_js:
  - "4.8"

dist: trusty
sudo: required

os:
  - linux
  - osx

addons:
  apt_packages:
    - graphicsmagick
    - python-virtualenv
    - libgmp3-dev
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  matrix:
  - TRAVIS_NODE_VERSION="4.8"

matrix:
  allow_failures:
    - os: osx
    - fast_finish: true

before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install graphicsmagick; fi

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - npm install -g npm@2
  - node --version
  - npm --version

script:
  - if [ $TRAVIS_NODE_VERSION == "4.8" ]; then export CXX=g++-4.8; fi
  - npm config set spin false
  - npm install
  - ./test/curl.sh

after_failure:
  - pm2 status
