language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"

services:
  - redis-server

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
    - node_js: "0.12"
    - node_js: "iojs"
    - fast_finish: true

before_install:
  - sudo apt-get install graphicsmagick
  - sudo apt-get install python-virtualenv
  - sudo apt-get install libgmp3-dev || brew install gmp
  - npm install -g npm@2.4
  - node --version
  - npm --version
  - npm config set spin false

script:
  - npm i
  - sleep 30
  - ./test/curl.sh
