language: node_js

addons:
  firefox: "66.0"

sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

node_js: '10'

script:
  - npm i
  - grunt lint
  - node_modules/.bin/ember test
