language: node_js

node_js:
  - "0.10"
  - "4"

sudo: false

notifications:
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

before_install:
  # Update to latest npm 2
  - npm install -g npm@2

install:
  - travis_retry npm install --silent

script:
  - npm test
  - grunt nsp --force
