language: node_js

node_js:
  - "6"

sudo: false

notifications:
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

install:
  - travis_retry npm install --silent

script:
  - npm test
  - grunt nsp --force
