language: node_js

node_js:
  - "0.10"
  - "0.12"

addons:
  firefox: "38.0"
env:
  global:
    - DISABLE_ROUTE_LOGGING=true

sudo: false

cache:
  directories:
    - node_modules
    - app/bower_components
    - fxa-auth-server/node_modules

notifications:
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

before_install:
  # Update to latest npm 2
  - npm install -g npm@2
  # Setup the xvfb environment. Read more at http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
  - java -jar selenium-server-standalone-2.45.0.jar &> /dev/null &

install:
  # install everything for full dev in the fxa-content-server.
  - travis_retry npm install --silent
  # copy over the configuration that can be used to start the server.
  - cp server/config/local.json-dist server/config/local.json
  # install the resources necessary for the auth server.
  - mkdir -p fxa-auth-server
  - cd fxa-auth-server && git init && git pull git://github.com/mozilla/fxa-auth-server.git --depth 1
  # first npm install will fail because there is no global GMP, we add localGmp after that failure
  - npm install
  # start the DB server
  - LOG_LEVEL=error node ./node_modules/fxa-auth-db-mysql/bin/mem.js &
  # start the auth server
  - node ./scripts/gen_keys.js
  - LOG_LEVEL=error npm start &
  - cd ..
  - npm start &
  - sleep 5

# now run the tests!
script:
  - npm ls --depth 0 | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'
  - grunt validate-shrinkwrap --force # check for vulnerable modules via nodesecurity.io
  - grunt lint
  - travis_retry npm run test-travis
  - travis_retry npm run test-server
