language: node_js
node_js:
  - "0.10"
addons:
  firefox: "29.0"
env:
  global:
    - DISABLE_ROUTE_LOGGING=true

before_install:
  # npm shrinkwrap broken on 1.4, see npm/issues/5787, 5920, 5692, downgrade:
  - npm install -g npm@1.3
  - sudo apt-get install libgmp3-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - java -jar selenium-server-standalone-2.41.0.jar &> /dev/null &
  - export FREIGHT_URL=https://freight.dev.lcip.org
  # See https://github.com/mozilla/fxa-content-server/issues/1483
  - npm config set spin false
  - npm install -g vladikoff/freight#v0.3.0 && freight

install:
  # install everything for full dev in the fxa-content-server.
  - travis_retry npm install --silent
  # copy over the configuration that can be used to start the server.
  - cp server/config/local.json-dist server/config/local.json
  # install the resources necessary for the auth server.
  - git clone git://github.com/mozilla/fxa-auth-server.git --depth 1
  - cd fxa-auth-server
  - freight
  - npm install --silent
  - node ./scripts/gen_keys.js
  - LOG_LEVEL=error npm start &
  - cd ..
  - npm start &
  - sleep 20

# now run the tests!
script:
  - npm outdated --depth 0 # show old modules
  - grunt validate-shrinkwrap --force # check for vulnerable modules via nodesecurity.io
  - grunt lint
  - travis_retry npm run test-travis
  - travis_retry npm run test-server
