language: node_js
node_js:
  - "0.10"
addons:
  firefox: "29.0"
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: fxa-content
    - SAUCE_ACCESS_KEY: ee5354a4-3d5e-47a0-84b0-0b7aaa12a720
    - DISABLE_ROUTE_LOGGING: true

before_install:
  - sudo apt-get install libgmp3-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - java -jar selenium-server-standalone-2.41.0.jar &> /dev/null &
  - export FREIGHT_URL=https://freight.dev.lcip.org
  # See https://github.com/mozilla/fxa-content-server/issues/1483
  - npm config set spin false
  - npm install -g vladikoff/freight#v0.3.0 && freight

install:
  # install everything for full dev in the fxa-content-server.
  - travis_retry npm install --silent
  # copy over the configuration that can be used to start the server.
  - cp server/config/local.json-dist server/config/local.json
  # install the resources necessary for the auth server.
  - git clone git://github.com/mozilla/fxa-auth-server.git --depth 1
  - cd fxa-auth-server
  - freight
  - npm install --silent
  - node ./scripts/gen_keys.js
  - LOG_LEVEL=error npm start &
  - sleep 10
  - cd ..
  - npm start &

# now run the tests!
script:
  - npm outdated --depth 0 # show old modules
  - grunt validate-shrinkwrap --force # check for vulnerable modules via nodesecurity.io
  - grunt lint
  - npm run test-server
  - travis_retry npm run test-travis
