[package]
name = "fxa-event-broker"
version = "1.138.4"
authors = ["FxA devs <fxa-core@mozilla.com>"]
edition = "2018"
publish = false

[profile.release]
# Include debug symbols to make Sentry errors richer
debug = 1

[dependencies]
config = ">=0.9.2"
failure = ">=0.1.5"
lazy_static = ">=1.3.0"
regex = ">=1.1.5"
rusoto_core = ">=0.37.0"
rusoto_credential = ">=0.16.0"
rusoto_sqs = ">=0.37.0"
sentry = ">=0.15.2"
serde = { version = ">=1.0.90", features = ["derive"] }
serde_json = ">=1.0.39"
