[package]
name = "fxa-email-service"
version = "0.1.0"

[dependencies]
chrono = { version = ">=0.4.2", features = [ "serde" ] }
config = ">=0.8.0"
futures = ">=0.1.21"
hex = ">=0.3.2"
lazy_static = ">=1.0"
md5 = ">=0.3.7"
regex = ">=1.0"
reqwest = ">=0.8.5"
rocket = ">=0.3.12"
rocket_codegen = ">=0.3.12"
rocket_contrib = ">=0.3.12"
rusoto_core = ">=0.32.0"
rusoto_credential = ">=0.11.0"
rusoto_ses = ">=0.32.0"
rusoto_sqs = ">=0.32.0"
sendgrid = ">=0.7.0"
serde = ">=1.0"
serde_derive = ">=1.0"
serde_json = ">=1.0"
validator = ">=0.6.3"
validator_derive = ">=0.6.5"

[[bin]]
name = "service"
path = "src/service_main.rs"

[[bin]]
name = "queues"
path = "src/queues_main.rs"
