[package]
name = "fxa_email_service"
version = "1.169.3"
publish = false
edition = "2018"

[[bin]]
name = "fxa_email_send"
path = "src/bin/service.rs"

[[bin]]
name = "fxa_email_queues"
path = "src/bin/queues.rs"

[profile.release]
# Include debug symbols to make Sentry errors richer
debug = true

[dependencies]
base64 = ">=0.6.0"
bytes = ">=0.4.12"
chrono = { version = ">=0.4.2", features = [ "serde" ] }
config = ">=0.9.1"
emailmessage = { git = "https://github.com/mozilla/emailmessage-rs.git", branch = "pb/unicode-local-address-part" }
failure = ">=0.1.2"
futures = ">=0.1.21,<0.2"
hex = ">=0.3.2"
hmac = ">=0.6.2"
http = ">=0.1.14"
hyperx = ">=0.13.2,<0.14"
lazy_static = ">=1.4.0"
lettre = ">=0.9.2"
lettre_email = ">=0.9.2"
md5 = ">=0.3.7"
rand = ">=0.5.1"
redis = ">=0.8.0"
regex = ">=1.0"
reqwest = ">=0.8.5"
rocket = ">=0.4.1"
rocket_codegen = ">=0.4.1"
rocket_contrib = { version = ">=0.4.1", default-features = false, features = ["json"] }
roxmltree = ">=0.3.0"
rusoto_core = ">=0.34.0"
rusoto_credential = ">=0.13.0"
rusoto_mock = ">=0.28.0"
rusoto_ses = ">=0.34.0"
rusoto_sqs = ">=0.34.0"
sendgrid = ">=0.7.2"
sentry = ">=0.12.0"
serde = ">=1.0"
serde_derive = ">=1.0"
serde_json = ">=1.0"
serde_test = ">=1.0.66"
sha2 = ">=0.7.1"
slog = ">=2.2.3"
slog-async = ">=2.3.0"
slog-mozlog-json = ">=0.1.0"
slog-scope = ">=4.0.1"
slog-term = ">=2.4.0"
socketlabs = ">=0.2.1"
tokio = ">=0.1.7"
uuid = { version = ">=0.6", features = ["v4"] }
