[package]
name = "fxa_email_service"
version = "1.121.0"
publish = false

[[bin]]
name = "fxa_email_send"
path = "src/bin/service.rs"

[[bin]]
name = "fxa_email_queues"
path = "src/bin/queues.rs"

[dependencies]
base64 = ">=0.6.0"
chrono = { version = ">=0.4.2", features = [ "serde" ] }
config = ">=0.9.1"
emailmessage = ">=0.1.0"
failure = ">=0.1.2"
futures = ">=0.1.21,<0.2"
hex = ">=0.3.2"
hmac = ">=0.6.2"
lazy_static = ">=1.0"
lettre = "0.8"
lettre_email = "0.8"
md5 = ">=0.3.7"
mozsvc-common = ">=0.1.0"
rand = ">=0.5.1"
redis = ">=0.8.0"
regex = ">=1.0"
reqwest = ">=0.8.5"
# Remove once a new version of rocket containing this commit is released.
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev="d7f6d82fe4d35ee79c424dd4164733b22f17f80a" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket", rev="d7f6d82fe4d35ee79c424dd4164733b22f17f80a" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", rev="d7f6d82fe4d35ee79c424dd4164733b22f17f80a" }
rusoto_core = { git = "https://github.com/brizental/rusoto", branch="request-body-params" }
rusoto_credential = { git = "https://github.com/brizental/rusoto", branch="request-body-params" }
rusoto_mock = { git = "https://github.com/brizental/rusoto", branch="request-body-params" }
rusoto_ses = { git = "https://github.com/brizental/rusoto", branch="request-body-params" }
rusoto_sqs = { git = "https://github.com/brizental/rusoto", branch="request-body-params" }
sendgrid = ">=0.7.1"
sentry = ">=0.7.0"
serde = ">=1.0"
serde_derive = ">=1.0"
serde_json = ">=1.0"
serde_test = ">=1.0.66"
sha2 = ">=0.7.1"
slog = ">=2.2.3"
slog-async = ">=2.3.0"
slog-mozlog-json = ">=0.1.0"
slog-scope = ">=4.0.1"
slog-term = ">=2.4.0"
socketlabs = ">=0.1.3"
tokio = ">=0.1.7"
uuid = { version = ">=0.6", features = ["v4"] }
