language: node_js

dist: trusty

sudo: required

node_js:
  - '8'

addons:
  apt_packages:
    - graphicsmagick
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

notifications:
  email:
    smcarthur@mozilla.com
    jrgm@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

env:
  - NODE_ENV=test DB=memory IMG=local
  - NODE_ENV=test DB=mysql IMG=local
  - NODE_ENV=test DB=mysql IMG=aws

before_install:
  - npm i -g npm@6
  - npm config set spin false
  - "mysql -e 'DROP DATABASE IF EXISTS fxa_profile;'"
  - "mysql -e 'CREATE DATABASE fxa_profile;'"

script:
  - npm run outdated
  - npm test
  # HACK: ignore npm audit errors for now until we get them all fixed
  - npm audit || true
